name: hypernerfgan
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - pip
  - pytorch
  - torchvision
  - imageio
  - protobuf=3.20.1
  - pip:
      - imageio-ffmpeg
      - hydra-core==1.0.6
      - click==7.1.2
      - scipy==1.6.1
      - ninja==1.10.0
      - tensorboard==2.4.1
      - tqdm==4.59.0
      - gitpython
      - opencv-python
      - -e .
